const SUPABASE_URL = "https://ifxpcofseejzobrueqvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_RBXrPe56Z76WP0b6wnzVDA_-w8QJX7bP";
const STRIPE_PRICE_PREMIUM = "price_1UMmGKG8lGvV5X1a9aYozK74";
const STRIPE_PRICE_VIP = "price_1UMmISG8lGvV5X1a7eOgOIQR";

const HTML = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>GLAMOUR LUXE — Premium Profiles</title>
<meta name="description" content="GLAMOUR LUXE — premium profile platform with verified listings and visibility plans.">
<meta name="theme-color" content="#050505">
<style>
:root{--bg:#050505;--panel:#0d0d0f;--panel2:#131316;--gold:#d4af37;--gold2:#f4d56a;--text:#f7f2df;--muted:#aaa59a;--line:rgba(212,175,55,.25);--green:#39d98a;--danger:#ff6678;--shadow:0 20px 70px rgba(0,0,0,.45)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 50% -10%,#29230e 0,#0a0906 24%,#050505 55%);color:var(--text);font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}a{color:inherit;text-decoration:none}button,input,textarea,select{font:inherit}button{cursor:pointer}
.top{padding:9px 16px;border-bottom:1px solid var(--line);background:#080806;font-size:12px;color:#c9c1aa;text-align:center}.top b{color:var(--gold2)}
header{position:sticky;top:0;z-index:20;background:rgba(5,5,5,.9);backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}.nav{max-width:1180px;margin:auto;display:flex;align-items:center;gap:20px;padding:14px 20px}.brand{font-family:Georgia,serif;letter-spacing:5px;font-size:24px;color:var(--gold);white-space:nowrap}.brand small{display:block;font:9px Inter,sans-serif;letter-spacing:3px;color:#b9b39f;text-align:center;margin-top:-2px}.links{margin-left:auto;display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.links button{background:transparent;border:0;color:#d8d3c6;padding:9px 11px;border-radius:10px}.links button:hover,.links button.active{color:var(--gold2);background:rgba(212,175,55,.08)}.hamb{display:none;margin-left:auto;background:none;border:1px solid var(--line);color:var(--gold);border-radius:10px;padding:8px}
main{max-width:1180px;margin:auto;padding:34px 20px 70px}.view{display:none}.view.active{display:block}.hero{min-height:480px;display:grid;place-items:center;text-align:center;padding:50px 15px}.hero h1{font:clamp(46px,9vw,88px) Georgia,serif;margin:0;color:var(--gold);letter-spacing:7px;text-shadow:0 0 35px rgba(212,175,55,.18)}.hero p{max-width:680px;margin:20px auto;color:var(--muted);font-size:17px;line-height:1.8}.actions{display:flex;gap:12px;justify-content:center;flex-wrap:wrap}.btn{border:1px solid var(--gold);background:linear-gradient(135deg,#d4af37,#f4d56a);color:#171207;font-weight:800;padding:12px 18px;border-radius:10px;box-shadow:0 8px 30px rgba(212,175,55,.13)}.btn.secondary{background:transparent;color:var(--gold2)}.btn.danger{border-color:var(--danger);background:transparent;color:#ff9aa7}.sectionTitle{display:flex;align-items:end;justify-content:space-between;gap:20px;margin:15px 0 20px}.sectionTitle h2{font:36px Georgia,serif;color:var(--gold);margin:0}.sectionTitle p{color:var(--muted);margin:5px 0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.card{background:linear-gradient(180deg,#111113,#09090a);border:1px solid var(--line);border-radius:18px;overflow:hidden;box-shadow:var(--shadow)}.photo{height:270px;background:#181818 center/cover no-repeat;position:relative}.badge{position:absolute;top:12px;left:12px;border-radius:999px;padding:6px 10px;font-size:11px;font-weight:800;background:#111;color:#fff;border:1px solid #555}.badge.vip{background:#d4af37;color:#171207;border-color:#f4d56a}.badge.verified{left:auto;right:12px;background:#092319;color:#65efad;border-color:#2bbf79}.body{padding:16px}.body h3{margin:0;color:#f6e6aa;font:25px Georgia,serif}.meta{color:#aaa;font-size:13px;margin:7px 0}.bio{color:#c5c1b8;line-height:1.6;font-size:14px;min-height:45px}.card .btn{width:100%;margin-top:10px}
.toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:20px}.field{background:#0c0c0d;border:1px solid #34302a;color:#f3efe3;border-radius:10px;padding:11px 13px;outline:none}.field:focus{border-color:var(--gold)}.search{flex:1;min-width:190px}.profileHero{display:grid;grid-template-columns:1fr 1fr;gap:22px}.gallery{display:grid;grid-template-columns:2fr 1fr 1fr;gap:8px}.gallery div{min-height:170px;background:#151515 center/cover no-repeat;border-radius:14px;border:1px solid var(--line)}.gallery div:first-child{min-height:420px;grid-row:span 2}.detail{padding:10px}.detail h1{font:48px Georgia,serif;color:var(--gold);margin:0}.detail .line{height:1px;background:var(--line);margin:18px 0}.tag{display:inline-block;border:1px solid var(--line);padding:7px 10px;border-radius:999px;margin:4px;color:#ddd}.plans{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.plan{padding:24px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(180deg,#131315,#080809)}.plan.featured{box-shadow:0 0 40px rgba(212,175,55,.13);border-color:#9d8124}.plan h3{font:30px Georgia,serif;color:#eee;margin:0}.price{font-size:40px;color:var(--gold);font-weight:900;margin:12px 0}.plan li{color:#bdb8ab;margin:10px 0}.form{max-width:720px;background:#0d0d0f;border:1px solid var(--line);border-radius:18px;padding:22px}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}.label{font-size:12px;color:#bdb7a8;margin:10px 0 6px}.field.full{width:100%}textarea.field{min-height:130px;resize:vertical}.notice{padding:12px 14px;border:1px solid var(--line);border-radius:12px;background:#0c0c0b;color:#c7c0ae;margin:12px 0}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.stat{padding:18px;border:1px solid var(--line);border-radius:15px;background:#0c0c0d}.stat b{display:block;font-size:30px;color:var(--gold)}footer{border-top:1px solid var(--line);padding:28px 20px;color:#777;text-align:center;font-size:12px}
.modal{position:fixed;inset:0;background:rgba(0,0,0,.76);display:none;place-items:center;padding:20px;z-index:50}.modal.open{display:grid}.modalBox{width:min(520px,100%);background:#0c0c0e;border:1px solid var(--gold);border-radius:18px;padding:24px;box-shadow:var(--shadow)}.modalBox h3{font:30px Georgia,serif;color:var(--gold);margin-top:0}.close{float:right;background:none;border:0;color:#aaa;font-size:26px}.toast{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);z-index:80;background:#111;border:1px solid var(--gold);color:#f5edcf;padding:12px 16px;border-radius:10px;display:none;max-width:90%;text-align:center}.toast.show{display:block}
@media(max-width:820px){.links{display:none}.links.open{display:flex;position:absolute;left:10px;right:10px;top:65px;background:#080808;border:1px solid var(--line);padding:10px;border-radius:14px;box-shadow:var(--shadow)}.hamb{display:block}.grid,.plans,.profileHero{grid-template-columns:1fr}.row{grid-template-columns:1fr}.gallery{grid-template-columns:1fr 1fr}.gallery div:first-child{grid-column:span 2;min-height:330px}.sectionTitle{display:block}.hero{min-height:420px}.nav{padding:12px 14px}.brand{font-size:20px}}
</style></head>
<body>
<div class="top"><b>GLAMOUR LUXE</b> — premium profile platform · secure account & visibility plans</div>
<header><nav class="nav"><button class="brand" onclick="go('home')">GLAMOUR<small>PREMIUM PROFILES</small></button><button class="hamb" onclick="toggleMenu()">☰</button><div id="navlinks" class="links"><button data-view="home" onclick="go('home')">Home</button><button data-view="explore" onclick="go('explore')">Explore Profiles</button><button data-view="vip" onclick="go('vip')">VIP</button><button data-view="plans" onclick="go('plans')">Plans & Payment</button><button data-view="create" onclick="go('create')">Create Profile</button><button data-view="account" onclick="go('account')">Account</button><button data-view="admin" onclick="go('admin')">Admin</button></div></nav></header>
<main>
<section id="home" class="view active"><div class="hero"><div><h1>GLAMOUR LUXE</h1><p>A refined platform for premium public profiles. Build a beautiful presence, verify your profile, and choose the visibility level that fits your goals.</p><div class="actions"><button class="btn" onclick="go('explore')">Explore Profiles</button><button class="btn secondary" onclick="go('create')">Create Your Profile</button></div></div></div><div class="sectionTitle"><div><h2>Featured Profiles</h2><p>Discover verified profiles with premium presentation.</p></div></div><div id="homeGrid" class="grid"></div></section>
<section id="explore" class="view"><div class="sectionTitle"><div><h2>Explore Profiles</h2><p>Search and open a profile for full details.</p></div></div><div class="toolbar"><input id="search" class="field search" placeholder="Search name, city or language" oninput="renderProfiles()"><select id="city" class="field" onchange="renderProfiles()"><option value="">All cities</option></select><select id="planFilter" class="field" onchange="renderProfiles()"><option value="">All plans</option><option value="premium">Premium</option><option value="vip">VIP</option><option value="basic">Basic</option></select></div><div id="profilesGrid" class="grid"></div></section>
<section id="vip" class="view"><div class="sectionTitle"><div><h2>VIP Profiles</h2><p>Top visibility tier with premium placement.</p></div></div><div id="vipGrid" class="grid"></div></section>
<section id="plans" class="view"><div class="sectionTitle"><div><h2>Plans & Payment</h2><p>Visibility plans are platform listing services. Payments are processed securely by Stripe.</p></div></div><div class="notice">Select one of your profiles below, then activate Premium or VIP. Your account must be signed in.</div><select id="paymentProfile" class="field full" style="width:100%;max-width:600px;margin-bottom:18px"></select><div class="plans"><div class="plan"><h3>Basic</h3><div class="price">Free</div><ul><li>Standard listing</li><li>Basic profile information</li><li>Standard placement</li></ul><button class="btn secondary" onclick="setBasic()">Use Basic</button></div><div class="plan featured"><h3>Premium</h3><div class="price">$19</div><small>30 days · one-time payment</small><ul><li>Premium badge</li><li>Featured placement</li><li>More profile visibility</li></ul><button class="btn" onclick="buyPlan('premium')">Pay & Activate</button></div><div class="plan featured"><h3>VIP</h3><div class="price">$49</div><small>30 days · one-time payment</small><ul><li>VIP badge</li><li>Top featured placement</li><li>Maximum platform visibility</li></ul><button class="btn" onclick="buyPlan('vip')">Pay & Activate VIP</button></div></div></section>
<section id="create" class="view"><div class="sectionTitle"><div><h2>Create Profile</h2><p>Create a public profile after signing in.</p></div></div><div class="form"><div class="notice">Profile owners are responsible for the accuracy and legality of their public information.</div><div class="row"><div><div class="label">Display name</div><input id="pname" class="field full" placeholder="e.g. Sienna"></div><div><div class="label">City</div><input id="pcity" class="field full" placeholder="e.g. Bangkok"></div></div><div class="row"><div><div class="label">Nationality</div><input id="pnationality" class="field full" placeholder="e.g. Thai"></div><div><div class="label">Languages</div><input id="planguages" class="field full" placeholder="English, Thai"></div></div><div class="label">Profile image URL</div><input id="pphoto" class="field full" placeholder="https://..."><div class="label">Second image URL (optional)</div><input id="pphoto2" class="field full" placeholder="https://..."><div class="label">Bio</div><textarea id="pbio" class="field full" placeholder="Write a concise professional profile description..."></textarea><button class="btn" onclick="createProfile()">Create Profile</button></div></section>
<section id="account" class="view"><div class="sectionTitle"><div><h2>Account</h2><p>Sign in or create your GLAMOUR LUXE account.</p></div></div><div class="form"><div id="accountStatus" class="notice">Not signed in.</div><div class="label">Email</div><input id="email" class="field full" type="email" placeholder="you@example.com"><div class="label">Password</div><input id="password" class="field full" type="password" placeholder="••••••••"><div class="actions" style="justify-content:flex-start;margin-top:14px"><button class="btn" onclick="signIn()">Sign In</button><button class="btn secondary" onclick="signUp()">Sign Up</button><button class="btn danger" onclick="signOut()">Sign Out</button></div></div></section>
<section id="admin" class="view"><div class="sectionTitle"><div><h2>Admin Panel</h2><p>Moderation and platform overview.</p></div></div><div id="adminContent" class="notice">Sign in with an authorized admin account.</div><div id="stats" class="stats" style="margin:18px 0"></div><div id="adminGrid" class="grid"></div></section>
</main><footer>© 2026 GLAMOUR LUXE · Premium Profile Platform · Secure payments by Stripe</footer>
<div id="modal" class="modal"><div class="modalBox"><button class="close" onclick="closeModal()">×</button><div id="modalContent"></div></div></div><div id="toast" class="toast"></div>
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>
<script>
const SB_URL=${JSON.stringify(SUPABASE_URL)}; const SB_KEY=${JSON.stringify(SUPABASE_PUBLISHABLE_KEY)}; const db=window.supabase.createClient(SB_URL,SB_KEY); window.glamourDB=db;
const demo=[{id:'demo-1',name:'Sienna',city:'Bangkok',nationality:'Thai',languages:['English','Thai'],bio:'Elegant professional profile with a refined presentation.',photo:'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?auto=format&fit=crop&w=900&q=85',photo2:'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=700&q=85',verified:true,active:true,plan:'vip'},{id:'demo-2',name:'Amelia',city:'Phuket',nationality:'British',languages:['English'],bio:'A polished public profile focused on premium presentation.',photo:'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?auto=format&fit=crop&w=900&q=85',verified:true,active:true,plan:'premium'},{id:'demo-3',name:'Luna',city:'Pattaya',nationality:'European',languages:['English','French'],bio:'Professional profile with a clean, modern aesthetic.',photo:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=900&q=85',verified:false,active:true,plan:'basic'}];
let profiles=[]; let session=null; let currentProfile=null;
function toast(x){const e=document.getElementById('toast');e.textContent=x;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),4000)}
function toggleMenu(){document.getElementById('navlinks').classList.toggle('open')}
function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));const el=document.getElementById(v);if(el)el.classList.add('active');document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.getElementById('navlinks').classList.remove('open');if(v==='explore')renderProfiles();if(v==='vip')renderVip();if(v==='plans')loadPaymentProfiles();if(v==='account')updateAccount();if(v==='admin')loadAdmin();scrollTo({top:0,behavior:'smooth'})}
function card(p){const img=p.photo||demo[0].photo;return \`<article class="card"><div class="photo" style="background-image:url('\${esc(img)}')">\${p.plan==='vip'?'<span class="badge vip">VIP</span>':''}\${p.verified?'<span class="badge verified">✓ Verified</span>':''}</div><div class="body"><h3>\${esc(p.name||'Profile')}</h3><div class="meta">\${esc(p.city||'')}\${p.nationality?' · '+esc(p.nationality):''}</div><div class="bio">\${esc(p.bio||'Premium public profile.')}</div><button class="btn secondary" onclick="openProfile('\${esc(p.id)}')">View Profile</button></div></article>\`}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function active(p){return p.active!==false && (!p.plan_expires_at || new Date(p.plan_expires_at)>new Date())}
async function loadProfiles(){try{const r=await fetch(SB_URL+'/rest/v1/profiles?select=*&active=eq.true&order=created_at.desc',{headers:{apikey:SB_KEY,Authorization:'Bearer '+SB_KEY}});if(r.ok){profiles=await r.json();if(!profiles.length)profiles=demo}else profiles=demo}catch(e){profiles=demo}renderProfiles();renderVip();document.getElementById('homeGrid').innerHTML=profiles.slice(0,3).map(card).join('');fillCities();}
function fillCities(){const s=document.getElementById('city');const cities=[...new Set(profiles.map(p=>p.city).filter(Boolean))];s.innerHTML='<option value="">All cities</option>'+cities.map(x=>\`<option>\${esc(x)}</option>\`).join('')}
function renderProfiles(){const q=(document.getElementById('search')?.value||'').toLowerCase();const c=document.getElementById('city')?.value||'';const pl=document.getElementById('planFilter')?.value||'';const arr=profiles.filter(p=>active(p)&&(!q||[p.name,p.city,p.nationality,(p.languages||[]).join(' ')].join(' ').toLowerCase().includes(q))&&(!c||p.city===c)&&(!pl||p.plan===pl));document.getElementById('profilesGrid').innerHTML=arr.length?arr.map(card).join(''):'<div class="notice">No profiles match your search.</div>'}
function renderVip(){const arr=profiles.filter(p=>active(p)&&p.plan==='vip');document.getElementById('vipGrid').innerHTML=arr.length?arr.map(card).join(''):'<div class="notice">No VIP profiles are currently active.</div>'}
function openProfile(id){const p=profiles.find(x=>String(x.id)===String(id));if(!p)return;currentProfile=p;const imgs=[p.photo,p.photo2].filter(Boolean);document.getElementById('modalContent').innerHTML=\`<div class="profileHero"><div class="gallery">\${imgs.map((x,i)=>\`<div style="background-image:url('\${esc(x)}')"></div>\`).join('')}</div><div class="detail"><h1>\${esc(p.name)}</h1><div class="meta">\${esc(p.city||'')} · \${esc(p.nationality||'')}</div><div>\${p.verified?'<span class="tag" style="color:#65efad">✓ Verified</span>':''}\${p.plan==='vip'?'<span class="tag" style="color:#f4d56a">VIP</span>':''}</div><div class="line"></div><p>\${esc(p.bio||'')}</p><div>\${(p.languages||[]).map(x=>\`<span class="tag">\${esc(x)}</span>\`).join('')}</div></div></div>\`;document.getElementById('modal').classList.add('open')}
function closeModal(){document.getElementById('modal').classList.remove('open')}
async function updateAccount(){const r=await db.auth.getSession();session=r.data.session;document.getElementById('accountStatus').textContent=session?'Signed in as '+session.user.email:'Not signed in.'}
async function signIn(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;const {error}=await db.auth.signInWithPassword({email,password});if(error)return toast(error.message);await updateAccount();toast('Signed in successfully.');loadPaymentProfiles()}
async function signUp(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(password.length<6)return toast('Password must be at least 6 characters.');const {error}=await db.auth.signUp({email,password});if(error)return toast(error.message);toast('Account created. Check your email if confirmation is enabled.');}
async function signOut(){await db.auth.signOut();session=null;updateAccount();toast('Signed out.')}
async function me(){const r=await db.auth.getUser();return r.data.user}
async function createProfile(){const user=await me();if(!user)return toast('Please sign in first.');const payload={owner_id:user.id,name:document.getElementById('pname').value.trim(),city:document.getElementById('pcity').value.trim(),nationality:document.getElementById('pnationality').value.trim(),languages:document.getElementById('planguages').value.split(',').map(x=>x.trim()).filter(Boolean),bio:document.getElementById('pbio').value.trim(),photo:document.getElementById('pphoto').value.trim(),photo2:document.getElementById('pphoto2').value.trim(),active:true,verified:false,plan:'basic'};if(!payload.name)return toast('Display name is required.');const {error}=await db.from('profiles').insert(payload);if(error)return toast(error.message);toast('Profile created.');await loadProfiles();go('explore')}
async function loadPaymentProfiles(){const user=await me();const sel=document.getElementById('paymentProfile');if(!sel)return;if(!user){sel.innerHTML='<option>Please sign in first</option>';return}const {data,error}=await db.from('profiles').select('id,name,plan').eq('owner_id',user.id).order('created_at',{ascending:false});if(error){sel.innerHTML='<option>Could not load profiles</option>';return}sel.innerHTML=data?.length?data.map(p=>\`<option value="\${esc(p.id)}">\${esc(p.name)} — \${(p.plan||'basic').toUpperCase()}</option>\`).join(''):'<option>No profiles yet</option>'}
async function buyPlan(plan){const user=await me();if(!user)return toast('Please sign in first.');const id=document.getElementById('paymentProfile').value;if(!id||id==='No profiles yet')return toast('Create a profile first.');toast('Opening secure Stripe Checkout…');try{const r=await fetch('/api/stripe/checkout',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+(await db.auth.getSession()).data.session.access_token},body:JSON.stringify({plan,profile_id:id})});const d=await r.json().catch(()=>({}));if(!r.ok)return toast('Checkout error: '+(d.error||'Payment service unavailable'));if(d.url)location.href=d.url;else toast('Stripe Checkout URL was not returned.')}catch(e){toast('Checkout connection error: '+e.message)}}
async function setBasic(){const user=await me();if(!user)return toast('Please sign in first.');const id=document.getElementById('paymentProfile').value;if(!id)return;const {error}=await db.from('profiles').update({plan:'basic',plan_expires_at:null}).eq('id',id).eq('owner_id',user.id);if(error)return toast(error.message);toast('Profile switched to Basic.');loadProfiles();loadPaymentProfiles()}
async function loadAdmin(){const user=await me();const box=document.getElementById('adminContent');if(!user){box.textContent='Sign in with an authorized admin account.';return}const {data}=await db.from('admins').select('user_id').eq('user_id',user.id).maybeSingle();if(!data){box.textContent='This account is not authorized as admin.';return}const {data:all,error}=await db.from('profiles').select('*').order('created_at',{ascending:false});if(error)return box.textContent=error.message;box.textContent='Admin access active.';document.getElementById('stats').innerHTML=\`<div class="stat"><span>Total profiles</span><b>\${all.length}</b></div><div class="stat"><span>Verified</span><b>\${all.filter(x=>x.verified).length}</b></div><div class="stat"><span>VIP</span><b>\${all.filter(x=>x.plan==='vip').length}</b></div>\`;document.getElementById('adminGrid').innerHTML=all.map(p=>\`<article class="card"><div class="body"><h3>\${esc(p.name)}</h3><div class="meta">\${esc(p.city||'')} · \${(p.plan||'basic').toUpperCase()}</div><div class="actions" style="justify-content:flex-start"><button class="btn secondary" onclick="adminVerify('\${esc(p.id)}',\${!p.verified})">\${p.verified?'Unverify':'Verify'}</button><button class="btn danger" onclick="adminToggle('\${esc(p.id)}',\${!p.active})">\${p.active?'Hide':'Activate'}</button></div></div></article>\`).join('')}
async function adminVerify(id,v){const {error}=await db.from('profiles').update({verified:v}).eq('id',id);if(error)return toast(error.message);toast(v?'Profile verified.':'Verification removed.');loadAdmin();loadProfiles()}
async function adminToggle(id,v){const {error}=await db.from('profiles').update({active:v}).eq('id',id);if(error)return toast(error.message);toast(v?'Profile activated.':'Profile hidden.');loadAdmin();loadProfiles()}
async function init(){await updateAccount();await loadProfiles();db.auth.onAuthStateChange(()=>updateAccount())}
init();
</script></body></html>`;

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization'}})}
function userToken(req){return req.headers.get('authorization')||''}
async function supabaseUser(req){const auth=userToken(req);if(!auth)return null;const r=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:auth}});return r.ok?await r.json():null}
async function createCheckout(req,env){if(!env.STRIPE_SECRET_KEY)return json({ok:false,error:'Stripe secret key is not configured.'},503);const user=await supabaseUser(req);if(!user)return json({ok:false,error:'Authentication required.'},401);let body;try{body=await req.json()}catch{return json({ok:false,error:'Invalid request body.'},400)}const plan=body?.plan,profileId=body?.profile_id;if(!['premium','vip'].includes(plan)||!profileId)return json({ok:false,error:'Invalid plan or profile.'},400);const p=await fetch(`${SUPABASE_URL}/rest/v1/profiles?id=eq.${encodeURIComponent(profileId)}&owner_id=eq.${encodeURIComponent(user.id)}&select=id,name,owner_id`,{headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:userToken(req)}});if(!p.ok){const detail=(await p.text()).slice(0,500);return json({ok:false,error:`Profile verification failed (${p.status}): ${detail}`},502)}const rows=await p.json();if(!rows.length)return json({ok:false,error:'Profile not found or not owned by this account.'},404);const priceId=plan==='vip'?STRIPE_PRICE_VIP:STRIPE_PRICE_PREMIUM;const origin=new URL(req.url).origin;const params=new URLSearchParams();params.set('mode','payment');params.set('line_items[0][price]',priceId);params.set('line_items[0][quantity]','1');params.set('success_url',`${origin}/payment?success=1&session_id={CHECKOUT_SESSION_ID}`);params.set('cancel_url',`${origin}/plans?cancelled=1`);params.set('client_reference_id',profileId);params.set('metadata[profile_id]',profileId);params.set('metadata[user_id]',user.id);params.set('metadata[plan]',plan);const sr=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,'Content-Type':'application/x-www-form-urlencoded'},body:params});const txt=await sr.text();let data;try{data=JSON.parse(txt)}catch{data={raw:txt}}if(!sr.ok)return json({ok:false,error:data?.error?.message||`Stripe returned HTTP ${sr.status}`},502);return json({ok:true,url:data.url,session_id:data.id})}
async function confirmPayment(req,env){if(!env.STRIPE_SECRET_KEY)return json({ok:false,error:'Stripe secret key is not configured.'},503);const u=new URL(req.url);const sessionId=u.searchParams.get('session_id');if(!sessionId)return json({ok:false,error:'Missing session_id.'},400);const sr=await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(sessionId)}?expand[]=payment_intent`,{headers:{Authorization:`Bearer ${env.STRIPE_SECRET_KEY}`}});const s=await sr.json();if(!sr.ok)return json({ok:false,error:s?.error?.message||'Stripe session lookup failed.'},502);if(s.payment_status!=='paid')return json({ok:false,error:'Payment is not completed.'},402);const profileId=s.metadata?.profile_id,userId=s.metadata?.user_id,plan=s.metadata?.plan;if(!profileId||!userId||!['premium','vip'].includes(plan))return json({ok:false,error:'Invalid payment metadata.'},400);const auth=req.headers.get('authorization');if(!auth)return json({ok:false,error:'Authentication required.'},401);const user=await supabaseUser(req);if(!user||user.id!==userId)return json({ok:false,error:'Account mismatch.'},403);const expiry=new Date(Date.now()+30*24*60*60*1000).toISOString();const r=await fetch(`${SUPABASE_URL}/rest/v1/profiles?id=eq.${encodeURIComponent(profileId)}&owner_id=eq.${encodeURIComponent(userId)}`,{method:'PATCH',headers:{apikey:SUPABASE_PUBLISHABLE_KEY,Authorization:auth,'Content-Type':'application/json','Prefer':'return=minimal'},body:JSON.stringify({plan,plan_expires_at:expiry,active:true})});if(!r.ok)return json({ok:false,error:`Profile activation failed (${r.status}).`},502);return json({ok:true,plan,expires_at:expiry})}
export default {async fetch(req,env){const u=new URL(req.url);if(req.method==='OPTIONS')return json({ok:true});if(u.pathname==='/api/health')return json({ok:true,service:'GLAMOUR LUXE',stripe:env.STRIPE_SECRET_KEY?'configured':'missing-secret',origin:u.origin});if(u.pathname==='/api/stripe/checkout'&&req.method==='POST')return createCheckout(req,env);if(u.pathname==='/api/stripe/confirm'&&req.method==='GET')return confirmPayment(req,env);if(u.pathname==='/payment'&&u.searchParams.get('success')==='1')return new Response(HTML.replace('</body>',`<script>setTimeout(async()=>{const r=await fetch('/api/stripe/confirm?session_id='+encodeURIComponent(new URL(location.href).searchParams.get('session_id')),{headers:{Authorization:'Bearer '+(await db.auth.getSession()).data.session?.access_token}});const d=await r.json().catch(()=>({}));toast(d.ok?'Payment confirmed — your plan is active.':('Payment confirmation: '+(d.error||'Unknown error')))},250)</script></body>`),{headers:{'content-type':'text/html;charset=utf-8'}});return new Response(HTML,{headers:{'content-type':'text/html;charset=utf-8','cache-control':'no-store'}})}};
